[package]
name = "raytracing"
version = "0.1.0"
authors = ["Aliaksei Labkovich <aliaksei.labkovich@itechart-group.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.22.3"
num_cpus="1.10.1"
